config/routes.rb
Rails.application.routes.draw do




  root 'home#index'

  resources :users do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]


  get 'doc_admin' => 'doc_admin#index'
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

 get '/users/mom_history/:id',  to: "users#mom_history", as: "user_mom_history"


 # get 'messages/reply'

 root 'messages#new'


 get 'messages/new'

 post 'messages/send'

 resource :messages do
   collection do

     post 'reply'

   end
 end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :length => { :minimum => 2 }
  validates :last_name, :length => { :minimum => 2 }
  validates :phone, :length => { :maximum => 14 }
  validates :email, confirmation: true, :uniqueness => true

  validates :password, presence: true, length: {minimum: 7, maximum: 120,
    too_short: "Password too short. Minimum 7 characters."}, on: :create
  validates :password, length: {minimum: 7, maximum: 120,
    too_short: "Password too short. Minimum 7 characters."}, on: :update, allow_blank: true

  scope :mothers, -> { where(mother: true) }
  has_secure_password
  has_many :comments

  def remaining_trimesters
     case trimester
     when 3
       [3]
     when 2
       [2, 3]
     else
       [1, 2, 3]
     end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
   @users = User.all
   @comment = Comment.new
 end

 def new
   @user = User.new
 end

 def show
   current_user
   @user = User.find(params[:id])

   @mothers = User.mothers
   @comment = Comment.new

   @my_comments = Comment.where(mother_id: @user.id, trimester_id: @user.trimester)
   @doctor = User.find_by(mother: false)     #this work because we only have one doctor.
 end

def create
  @user = User.new(user_params)
  @user.mother = true

  if @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user.id), notice: "Sucessfully signed up!"
  else
    render :new, notice: "Please try again."
  end
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])

  if params[:user] != nil && params[:user][:trimester] != nil && @user.trimester != params[:user][:trimester] && @user.update(user_params)
    redirect_to user_url(@user),
    notice: "Your trimester stage has been updated."
    return
  end

  # Check if fields are not empty when mother is answering trimester questions.
  if params[:user] != nil && current_user.trimester != nil
      if (@user.trimester == 1 && (params[:user]['tri_1_1'] == nil ||
            params[:user]['tri_1_2'] == nil || params[:user]['tri_1_3'] == nil)) ||
            (@user.trimester == 2 && (params[:user]['tri_2_1'] == nil ||
            params[:user]['tri_2_2'] == nil || params[:user]['tri_2_3'] == nil)) ||
            (@user.trimester == 3 && (params[:user]['tri_3_1'] == nil ||
            params[:user]['tri_3_2'] == nil || params[:user]['tri_3_3'] == nil))
          redirect_to user_url(@user), notice: "Error: Please answer all of the questions."
          return
      else
          @user.update(user_params)
          redirect_to user_url(current_user),
          notice: "Your answers successfully logged."
          return
      end
  else
    redirect_to user_url(@user), notice: "Error Updating."
    return
  end

end

  def mom_history
    @user = User.find(params[:id])
    @comments = Comment.where(mother_id: params[:id])
    @doctor = User.find_by(mother: false)     #this work because we only have one doctor.

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
    :password_confirmation, :phone, :address, :dob, :children, :trimester,
    :tri_1_1, :tri_1_2, :tri_1_3, :tri_2_1, :tri_2_2, :tri_2_3,
    :tri_3_1, :tri_3_2, :tri_3_3, :doc_qual, :regis_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def trimesters_for_select
    current_user.remaining_trimesters.map { |trimester| [trimester_as_words(trimester), trimester] }
  end

 def trimester_as_words(trimester)
   case trimester
   when 1
     'First Trimester'
   when 2
     'Second Trimester'
   when 3
     'Third Trimester'
   end
 end

end

app/views/users/_doc_form.html.erb
  <p>
    <%= f.label :qualifications %>
    <%= f.text_field :doc_qual, :maxlength => 18 %>
  </p>

  <p>
    <%= f.label :registration_number %>
    <%= f.text_field :regis_number, :maxlength => 18 %>
  </p>

app/views/users/_doc_profile.html.erb
<%= image_tag "logo3.png", :width => "204", :height => "106", class: "mommylogo"%>

  <div class="profile-wrapper animated fadeIn">
    <div class="doc-profile">

      <div class="notice">
        <% if notice != nil %>
          <p style="color: red; font-weight: bold;"><%= notice %></p>
        <% end %>
      </div>

      <%= image_tag "diagnostics-161140.png", :width => "100", :height => "120", class: "doc-img" %>
      <h3 class="page-title">Doctor Profile</h3>

        <div class="prof1">
          <p>name:</p>
          <p>address:</p>
          <p>phone number:</p>
          <p>email:</p>
          <p>registration number:</p>
          <p>qualifications:</p>
        </div>

        <div class="prof2">
          <p><%= " #{@user.first_name.titleize} #{@user.last_name.titleize}" %></p>
          <p><%= " #{@user.address}" %></p>
          <p><%= " #{@user.phone}" %></p>
          <p><%= " #{@user.email}" %></p>
          <p><%= " #{@user.regis_number}" %></p>
          <p><%= " #{@user.doc_qual}" %></p>
        </div>

          <div class="doc-list">
            <div class="page-title">
              <p><%= link_to "Send Text To Patient", messages_new_path, class: "doc-btn" %></p>
              <h3 class="page-title">List of Patients:</h3>
            </div>
            <% if current_user == @doctor %>
              <% @mothers.each do |mother|%>
              <li><%= link_to "#{mother.first_name} #{mother.last_name}", mother %></li>
              <% end %>
            <%end%>

          </div>

    </div>
  </div>

app/views/users/_mom_profile.html.erb
<div class="mommylogo">
  <%= image_tag "logo3.png", :width => "204", :height => "106" %>
</div>

  <div class="profile-wrapper animated fadeIn">
    <div class="profile">

      <div class="notice">
        <% if notice != nil %>
          <p style="color: red; font-weight: bold;"><%= notice %></p>
        <% end %>
      </div>

        <h3 class="page-title"><%= "Mommy #{@user.first_name}" %> Profile</h3>

        <% if current_user.mother == true %>
        <%= link_to "My History", user_mom_history_path, class: "mom-btn" %>
        <% else %>
        <%= link_to "#{@user.first_name}'s History", user_mom_history_path, class: "mom-btn" %>
        <% end %>

          <p>
            <div class="prof1">
              <p>name: </p>
              <p>address: </p>
              <p>phone number: </p>
              <p>email: </p>
              <p>date of birth: </p>
              <p>number of children: </p>
            </div>

            <div class="prof2">
              <p><%= " #{@user.first_name.titleize} #{@user.last_name.titleize}" %></p>
              <p><%= " #{@user.address}" %></p>
              <p><%= " #{@user.phone}" %></p>
              <p><%= " #{@user.email}" %></p>
              <p><%= " #{@user.dob}" %></p>
              <p><%= " #{@user.children}" %></p>
            </div>

      <div class="mom-stage">
        <%= image_tag "pregnancy-stg.png", :width => "204", :height => "106" %>

          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>

            <%= form_for @user do |f| %>
              <% if current_user.mother == true %>

                  <p class="page-title"><strong>Current Stage of Pregnancy:</strong></p>
                  <p>
                   <%=
                     f.select(:trimester,
                     options_for_select(
                     trimesters_for_select,
                      selected: current_user.trimester))
                   %>
                  <%= f.submit 'Update' %>
                 </p>
              <% end %>
            <% end %>
      </div>

        <div class="tri-question">
          <% if @user.trimester == 1 %>
            <%=  render 'tri_1_QA'%>
            <% elsif @user.trimester == 2 %>
            <%=  render 'tri_2_QA'%>
            <% else %>
            <%=  render 'tri_3_QA'%>
          <% end %>
        </div>

      <div class="tri-question">
          <% @my_comments.each do |comment| %>
            <% if comment.doctor_id == nil %>
            <div class="mom-cmnt">
              <%= image_tag "pregnancy-with-hearts(1)copy.png", :width => "50", :height => "70", class: "mini-mom" %>
                <div class="mom-cmnt2">
                    <p class="mom"><%= "#{@user.first_name}:" %></p>
                    <p class="comnt"><%= comment.comment %></p>
                    <p class="time"><%= comment.created_at.in_time_zone('Eastern Time (US & Canada)').to_formatted_s(:long_ordinal) %></p>
                </div>
            </div>
            <%else%>
            <div class="doc-cmnt">
              <%= image_tag "steth-icon.png", :width => "50", :height => "70", class: "mini-doc" %>
               <div class="doc-comnt2">
                  <p class="doc"><%= "#{@doctor.first_name}:" %></p>
                  <p class="comnt"><%= comment.comment %></p>
                  <p class="time"><%= comment.created_at.in_time_zone('Eastern Time (US & Canada)').to_formatted_s(:long_ordinal) %></p>
               </div>
            </div>
            <% end %>
          <% end %>
      </div>

    </div>
</div>

app/views/users/_mommy_form.html.erb
    <p>
    <%= label_tag :stage_of_pregnancy %>
    <%=
      f.select(:trimester,
      options_for_select(
      [['Please select one', ''],
       ['First Trimester', 1],
       ['Second Trimester', 2],
       ['Third Trimester', 3]]))
    %>
    </p>

    <p>
      <%= f.label :date_of_birth %>
      <%= f.date_field :dob %>
    </p>

    <p>
      <%= f.label :number_of_children %>
      <%= f.number_field :children %>
    </p>

app/views/users/_tri_1_QA.html.erb
<h3>FIRST TRIMESTER QUESTION</h3>

  <% if current_user.mother == true %>

    <%= form_for @user do |f|%>
      <%
       question_answered = false
       if current_user.tri_1_1 != nil &&
             current_user.tri_1_2 != nil &&
             current_user.tri_1_3 != nil
           question_answered = true
       end
      %>

        <p>
          1. Are you having any cramps or pain?
         <% if question_answered == true %>
         <b><%= current_user.tri_1_1 %></b>
         <% end %>
        </p>

        <% if question_answered == false %>
          <ul>
             <%= f.label :tri_1_1, "Yes" %>
             <%= f.radio_button :tri_1_1, "Yes" %>
             <%= f.label :tri_1_1, "No" %>
             <%= f.radio_button :tri_1_1, "No" %>
             <%= f.label :tri_1_1, "N/A" %>
             <%= f.radio_button :tri_1_1, "N/A" %>
          </ul>
        <% end %>

        <p>
          2. Do you feel feverish with a very high body temperature?
          <% if question_answered == true %>
          <b><%= current_user.tri_1_2 %></b>
          <% end %>
        </p>

        <% if question_answered == false %>
          <ul>
            <%= f.label :tri_1_2, "Yes" %>
            <%= f.radio_button :tri_1_2, "Yes" %>
            <%= f.label :tri_1_2, "No" %>
            <%= f.radio_button :tri_1_2, "No" %>
            <%= f.label :tri_1_2, "N/A" %>
            <%= f.radio_button :tri_1_2, "N/A" %>
          </ul>
        <% end %>

        <p>
          3. Are you having excessive nausea and vomitting?
         <% if question_answered == true %>
          <b><%= current_user.tri_1_3 %></b>
         <% end %>
        </p>

        <% if question_answered == false %>
          <ul>
            <%= f.label :tri_1_3, "Yes" %>
            <%= f.radio_button :tri_1_3, "Yes" %>
            <%= f.label :tri_1_3, "No" %>
            <%= f.radio_button :tri_1_3, "No" %>
            <%= f.label :tri_1_3, "N/A" %>
            <%= f.radio_button :tri_1_3, "N/A" %>
          </ul>

        <% end %>


          <p><%= f.submit 'Update' %></p>
    <% end %>


  <% else %>

        <p>
          1. Are you having any cramps or pain?
            <ul><li><%= @user.tri_1_1 %></li></ul>
        </p>

         <p>
          2. Do you feel feverish with a very high body temperature?
            <ul><li><%= @user.tri_1_2 %></li></ul>
         </p>

         <p>
           3. Are you having excessive nausea and vomitting?
             <ul><li><%= @user.tri_1_3 %></li></ul>
          </p>

      <% end %>


      <% if current_user.tri_2_1 == nil && current_user.tri_2_2 == nil && current_user.tri_2_3 == nil %> <!--once mother answer questions on 2nd trimester, they cannot create comment on 1st trimester.-->
         <%= render 'comments/comment_form'%>
      <% end %>

app/views/users/_tri_2_QA.html.erb
<h3 class="page-title">Second Trimester Question</h3>

  <% if current_user.mother == true %>

    <%= form_for @user do |f|%>
      <%
        question_answered = false
          if current_user.tri_2_1 != nil &&
                current_user.tri_2_2 != nil &&
                current_user.tri_2_3 != nil
              question_answered = true
          end
      %>

      <p>
        1. Are you having an increase pelvic pressure and/or unusual discharge, eg. bleeding?
          <% if question_answered == true %>
            <b><%= current_user.tri_2_1 %></b>
          <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
          <%= f.label :tri_2_1, "Yes" %>
          <%= f.radio_button :tri_2_1, "Yes" %>
          <%= f.label :tri_2_1, "No" %>
          <%= f.radio_button :tri_2_1, "No" %>
          <%= f.label :tri_2_1, "N/A" %>
          <%= f.radio_button :tri_2_1, "N/A" %>
        </ul>
      <% end %>


      <p>
        2. Are you having headaches that are not relieved with over-the-counter
        medications or have visual changes associated with them, persistent vomiting, and upper abdominal pain?
          <% if question_answered == true %>
            <b><%= current_user.tri_2_2 %></b>
          <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
          <%= f.label :tri_2_2, "Yes" %>
          <%= f.radio_button :tri_2_2, "Yes" %>
          <%= f.label :tri_2_2, "No" %>
          <%= f.radio_button :tri_2_2, "No" %>
          <%= f.label :tri_2_2, "N/A" %>
          <%= f.radio_button :tri_2_2, "N/A" %>
        </ul>
      <% end %>


      <p>
        3.  Do any of these symptoms apply to you? Vaginal pressure, Low-back pain, Frequent urination, Diarrhea, Increased vaginal discharge, Tightness in the lower abdomen
          <% if question_answered == true %>
            <b><%= current_user.tri_2_3 %></b>
          <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
          <%= f.label :tri_2_3, "Yes" %>
          <%= f.radio_button :tri_2_3, "Yes" %>
          <%= f.label :tri_2_3, "No" %>
          <%= f.radio_button :tri_2_3, "No" %>
          <%= f.label :tri_2_3, "N/A" %>
          <%= f.radio_button :tri_2_3, "N/A" %>
        </ul>
      <% end %>

        <p><%= f.submit 'Update' %></p>
  <% end %>

<% else %>

      <p>
        1. Are you having an increase pelvic pressure and/or unusual discharge, eg. bleeding?
         <ul><li><%= @user.tri_2_1 %></li></ul>
      </p>

      <p>
        2. Are you having headaches that are not relieved with over-the-counter
          medications or have visual changes associated with them, persistent vomiting, and upper abdominal pain?
         <ul><li><%= @user.tri_2_2 %></li></ul>
      </p>

      <p>
        3.  Do any of these symptoms apply to you? Vaginal pressure, Low-back pain, Frequent urination, Diarrhea, Increased vaginal discharge, Tightness in the lower abdomen
        <ul><li><%= @user.tri_2_3 %></li></ul>
      </p>

  <% end %>


  <% if current_user.tri_3_1 == nil && current_user.tri_3_2 == nil && current_user.tri_3_3 == nil %> <!--once mother answer questions on 2nd trimester, they cannot create comment on 1st trimester.-->
    <%= render 'comments/comment_form'%>
  <% end %>

app/views/users/_tri_3_QA.html.erb
<div class="tri-title">
  <h3 class="page-title">Third Trimester Question</h3>
</div>

 <% if current_user.mother == true %>

    <%= form_for @user do |f|%>
        <%
         question_answered = false
         if current_user.tri_3_1 != nil &&
               current_user.tri_3_2 != nil &&
               current_user.tri_3_3 != nil
             question_answered = true
         end
        %>

      <p>
        1. Are you having headaches that are not relieved with over-the-counter
        medications or have visual changes associated with them, persistent vomiting,
        and upper abdominal pain?
           <% if question_answered == true %>
            <p><b><%= current_user.tri_3_1 %></b></p>
           <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
           <%= f.label :tri_3_1, "Yes" %>
           <%= f.radio_button :tri_3_1, "Yes" %>
           <%= f.label :tri_3_1, "No" %>
           <%= f.radio_button :tri_3_1, "No" %>
           <%= f.label :tri_3_1, "N/A" %>
           <%= f.radio_button :tri_3_1, "N/A" %>
        </ul>
      <% end %>


      <p>
        2. Is there decreased movement from your baby?
           <% if question_answered == true %>
             <p><b><%= current_user.tri_3_2 %></b></p>
           <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
           <%= f.label :tri_3_2, "Yes" %>
           <%= f.radio_button :tri_3_2, "Yes" %>
           <%= f.label :tri_3_2, "No" %>
           <%= f.radio_button :tri_3_2, "No" %>
           <%= f.label :tri_3_2, "N/A" %>
           <%= f.radio_button :tri_3_2, "N/A" %>
        </ul>
      <% end %>


      <p>
        3. Do any of these changes apply to you?  Vaginal discharge to a pink or
        reddish color, menstrual-like cramps, pressure in your pelvis or lower abdomen,
        and contractions that last for at least an hour that aren’t Braxton Hicks contractions.
           <% if question_answered == true %>
             <p><b><%= current_user.tri_3_3 %></b><p>
           <% end %>
      </p>

      <% if question_answered == false %>
        <ul>
           <%= f.label :tri_3_3, "Yes" %>
           <%= f.radio_button :tri_3_3, "Yes" %>
           <%= f.label :tri_3_3, "No" %>
           <%= f.radio_button :tri_3_3, "No" %>
           <%= f.label :tri_3_3, "N/A" %>
           <%= f.radio_button :tri_3_3, "N/A" %>
        </ul>
      <% end %>

      <p><%= f.submit 'Reply' %></p>

    <% end %>

 <% else%>

     <p>
       1. Are you having headaches that are not relieved with over-the-counter
      medications or have visual changes associated with them, persistent vomiting,
      and upper abdominal pain?
        <ul><li><%= @user.tri_3_1 %></li></ul>
     </p>

     <p>
       2. Is there decreased movement from your baby?
         <ul><li><%= @user.tri_3_2 %></li></ul>
     </p>

     <p>
       3. Do any of these changes apply to you?  Vaginal discharge to a pink or
       reddish color, menstrual-like cramps, pressure in your pelvis or lower abdomen,
       and contractions that last for at least an hour that aren’t Braxton Hicks contractions.
         <ul><li><%= @user.tri_3_3 %></li></ul>
     </p>

<% end %>

<br/>

   <%= render 'comments/comment_form'%>

app/views/users/_user_form.html.erb
  <% if @user.errors.any? %>
    <h2>Invalid form. Please try again.</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "first name" %>
    </p>

    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "last name" %>
    </p>

    <p>
      <p><%= f.label :email %></p>
      <%= f.text_field :email, placeholder: "you@email.com" %>
    </p>

    <p>
      <%= f.label :phone_number %>
      <%= f.text_field :phone, placeholder: "123-456-7890" %>
    </p>

    <p>
      <%= f.label :address %>
      <%= f.text_field :address, placeholder: "eg. 123 Some Street" %>
    </p>

    <p>
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "password" %>
    </p>

    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, placeholder: "password confirmation" %>
    </p>

app/views/users/edit.html.erb
<div class="container">

<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

</div>

app/views/users/home.html.erb
<%= link_to "Login", {:controller=> "sessions", :action=> "new"}, :method => :get %> |
<%= link_to "Sign Up", {:controller=> "users", :action=> "new"}, :method => :get %>


<h1>Mommy Monitor</h1>

<p>An expectant mother? Connecting with your specialist has just gotten easier!</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

app/views/users/new.html.erb
<%= image_tag "logo3.png", :width => "204", :height => "106", class: "mommylogo"%>

<div class="container">
  <div class="field2 animated fadeInUp">
    <div class="field-input2">

      <h3 class="login-title">sign-up</h3>

        <%= form_for @user do |f| %>

          <%= render 'user_form', f: f %>

            <h4 id="r1">Click if you're a Mommy!</h4>
              <div class="role1">
                <p><%= render 'mommy_form', f: f %></p>
              </div>


            <h4 id="r2">Click if you're a Doctor!</h4>
              <div class="role2">
                <p><%= render 'doc_form', f: f %></p>
              </div>

              <%= f.submit 'Submit', class: "login-btn" %>

        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">

  <% if @user.mother == false %>
    <%= render 'doc_profile'%>
    <% else %>
    <%= render 'mom_profile'%>
  <% end %>

</div>